---
title: "Pinçando postos"
author: "Doriedson"
date: "2024-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Requisitos, include=FALSE}
require(dplyr)
require(ggplot2)

source("abrev.R")

```

```{r DADOS, include=FALSE}
dados3 = read.csv(dados_completos)

dados3 = dados3[, -c(1, 2, 7)]

aux = as.Date(dados3$Data.da.Coleta, format = "%d/%m/%Y")
dados3$Data.da.Coleta <- aux

aux = stringr::str_replace_all(dados3$Valor.de.Venda, ",", ".")
dados3$Valor.de.Venda <-as.numeric(aux)

aux = format(dados3$Data.da.Coleta, "%Y-%m")
dados3$grupo <- aux
rm(aux)

#cat("Base de dados com todas observações de Goiânia!")
#summary(dados3)

# Somente gasolina
dados3g = subset(dados3, dados3$Produto == "GASOLINA")
rm(dados3)

```


```{r}
# Carregar os pacotes necessários
library(dplyr)
library(ggplot2)

# Exemplo de dataframe
df <- data.frame(
  letra = c('A', 'A', 'B', 'B', 'C', 'C', 'A', 'B', 'C', 'A'),
  data = as.Date(c('2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03', '2024-01-03', '2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04'))
)

# Remover linhas duplicadas
df_unique <- df %>%
  distinct(letra, data)

# Criar uma coluna de contagem cumulativa para cada letra
df_unique <- df_unique %>%
  group_by(letra) %>%
  arrange(data) %>%
  mutate(contagem_cumulativa = row_number())

# Criar o gráfico de linha com ggplot
ggplot(df_unique, aes(x = data, y = contagem_cumulativa, color = letra, group = letra)) +
  geom_line() +
  geom_point() +
  labs(title = "Evolução da Contagem de Cada Letra", x = "Data", y = "Contagem Cumulativa") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "1 day") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}
head(dados3g)
df = dados3g[, c(1, 3)]

colnames(df) <- c("nome", "data")

# Remover linhas duplicadas
df_unique <- df %>%  distinct(nome, data)

# Criar uma coluna de contagem cumulativa para cada letra
df_unique <- df_unique %>%
  group_by(nome) %>%
  arrange(data) %>%
  mutate(contagem_cumulativa = cumsum(!duplicated(data)))

# Criar o gráfico de linha com ggplot
g1=ggplot(df_unique,
          aes(x = data, y = contagem_cumulativa, color = nome, group = nome)) +
  geom_line() +
  geom_point() +
  labs(title = "Evolução da Contagem de Cada Letra",
       x = "Data", y = "Contagem Cumulativa") +
  theme_minimal() +
  theme(legend.position = 'none') +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "90 days") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plotly::ggplotly(g1)

```

