---
title: "Pinçando postos"
author: "Doriedson"
date: "2024-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Requisitos, include=FALSE}
require(dplyr)
require(ggplot2)

source("abrev.R")

```

```{r DADOS, include=FALSE}
dados3 = read.csv(dados_completos)

dados3 = dados3[, -c(1, 2, 7)]

aux = as.Date(dados3$Data.da.Coleta, format = "%d/%m/%Y")
dados3$Data.da.Coleta <- aux

aux = stringr::str_replace_all(dados3$Valor.de.Venda, ",", ".")
dados3$Valor.de.Venda <-as.numeric(aux)

aux = format(dados3$Data.da.Coleta, "%Y-%m")
dados3$grupo <- aux
rm(aux)

#cat("Base de dados com todas observações de Goiânia!")
#summary(dados3)

# Somente gasolina
dados3g = subset(dados3, dados3$Produto == "GASOLINA")
dados3g[order(dados3g$Data.da.Coleta), ]

dados3g = dados3g[-c(1:16680), ]

rm(dados3)

```

```{r}
head(dados3g)
df = dados3g[, c(1, 3)]

colnames(df) <- c("nome", "data")

# Remover linhas duplicadas
df_unique <- df %>%  distinct(nome, data)

# Criar uma coluna de contagem cumulativa para cada letra
df_unique <- df_unique %>%
  group_by(nome) %>%
  arrange(data) %>%
  mutate(contagem_cumulativa = cumsum(!duplicated(data)))

# Calcular o tempo de espera para cada letra
df_wait_time <- df_unique %>% group_by(nome) %>% arrange(data) %>%
  mutate(tempo_espera = as.numeric(difftime(data, lag(data), units = "days"))) %>%
  filter(!is.na(tempo_espera))

# Obter o tempo médio de espera para cada letra
df_tempo_medio <- df_wait_time %>% group_by(nome) %>%
  summarise(tempo_medio_espera = mean(tempo_espera, na.rm = TRUE)) %>%
  arrange(tempo_medio_espera)

vetor = c()
for(x in df_tempo_medio$nome){
  df_aux = subset(df, df$nome == x)
  tamanho = dim(df_aux)[1]
  vetor = c(vetor, tamanho)
}
df_tempo_medio = cbind(df_tempo_medio, tamanho=vetor)
rm(vetor)

#subset(df, df$nome == df_tempo_medio$nome[10])

# Obter a letra com o menor tempo de espera médio 
#letra_menor_tempo_espera <- df_wait_time %>% group_by(nome) %>%
#  summarise(tempo_medio_espera = mean(tempo_espera, na.rm = TRUE)) %>%
#  arrange(tempo_medio_espera) %>% slice(1)

# Criar o gráfico de linha com ggplot
g1=ggplot(df_unique,
          aes(x = data, y = contagem_cumulativa, color = nome, group = nome)) +
  geom_line() +
  geom_point() +
  labs(title = "Evolução da Contagem de Cada Posto",
       x = "Data", y = "Contagem Cumulativa") +
  theme_minimal() +
  theme(legend.position = 'none') +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "90 days") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plotly::ggplotly(g1)

```
```{r}
#View(df_tempo_medio)

df_tempo_medio[1:10, ]

```


O posto "POSTO XODO LTDA" é o revendedor que mais tem observações com 365. Também possui o 4º menor tempo de espera entre cada observação.

```{r}
aux = subset(dados3g, dados3g$Revenda == df_tempo_medio$nome[4])
head(aux)

g1 = ggplot(data = aux, aes(x=Data.da.Coleta, y=Valor.de.Venda)) +
  geom_point() +
  labs(title = "Evolução do preço da gasolina (REVENDEDOR PX)", x = "Data", y = "Valor") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "365 days") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plotly::ggplotly(g1)

```

